services:
  mc-o11y-agent:
    image: cloudbaristaorg/mc-observability:edge
    container_name: mc-o11y-agent
    restart: always
    ports:
      - 18081:18081
    environment:
      - NS_ID=${NS_ID}
      - MCI_ID=${MCI_ID}
      - TARGET_ID=${TARGET_ID}
      - TUMBLEBUG_URL=${TUMBLEBUG_URL}
      - TUMBLEBUG_ID=${TUMBLEBUG_ID}
      - TUMBLEBUG_PW=${TUMBLEBUG_PW}
      - SPIDER_URL=${SPIDER_URL}
      - SPIDER_MONITORING_INFLUXDB_URL=${SPIDER_MONITORING_INFLUXDB_URL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_ID=${DATABASE_ID}
      - DATABASE_PW=${DATABASE_PW}
    volumes:
      - /etc/:/etc/:rw
      - /usr/lib/os-release:/usr/lib/os-release:ro
      - /var/:/var/:rw
