networks:
  internal_network:
    internal: true
  external_network:
    driver: bridge

services:
  o11y-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: o11y-manager:latest
    container_name: o11y-manager
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./applog:/applog
    healthcheck:
      start_period: 120s
      test: 'curl -s http://127.0.0.1:18080/api/docs ; STATUS=`echo $$?` ; if [ $$STATUS != 0 ] && [ $$STATUS != 52 ]; then exit 1 ; fi'
      interval: 10s
      timeout: 10s
      retries: 30

  mc-o11y-manager:
    image: cloudbaristaorg/mc-observability:edge
    container_name: mc-o11y-service
    restart: always
    ports:
      - 18080:18080
      - 18081:18081
    networks:
      - internal_network
      - external_network
    environment:
      - TARGET_ID=mc-o11y
      - TUMBLEBUG_URL=${TUMBLEBUG_URL:-http://cb-tumblebug:1323}
      - TUMBLEBUG_ID=${TUMBLEBUG_ID:-default}
      - TUMBLEBUG_PW=${TUMBLEBUG_PW:-default}
      - SPIDER_URL=${SPIDER_URL:-http://cb-spider:1024}
      - SPIDER_ID=${SPIDER_ID:-}
      - SPIDER_PW=${SPIDER_PW:-}
      - INSIGHT_URL=http://mc-o11y-insight:9001
    volumes:
      - ./manager-conf:/etc/mc-observability-agent/conf:rw
      - /var/log/syslog:/var/log/syslog:ro

  mariadb:
    image: mariadb:10.7.6
    container_name: mc-o11y-maria
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - /docker/mariadb/var/lib/mysql:/var/lib/mysql
      - /docker/mariadb/var/log/maria:/var/log/maria
      - ./maria_init.sql:/docker-entrypoint-initdb.d/maria_init.sql
      - ./mariadb-conf/99-max-connections.cnf:/etc/mysql/mariadb.conf.d/99-max-connections.cnf
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=qwe1212!Q
      - MARIADB_USER=mc-agent
      - MARIADB_DATABASE=mc_observability
      - MARIADB_PASSWORD=mc-agent
    networks:
      - internal_network
      - external_network

  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:0.10.9
    container_name: cb-tumblebug
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal_network
      - external_network
      # - terrarium_network # Uncomment this line when you use this compose and the terrarium compose
    ports:
      - 1323:1323
    depends_on:
      cb-tumblebug-etcd:
        condition: service_started
      cb-spider:
        condition: service_started
      cb-tumblebug-postgres:
        condition: service_healthy
    volumes:
      - ./conf/setup.env:/app/conf/setup.env
      - ./conf/cloud_conf.yaml:/app/conf/cloud_conf.yaml
      - ~/.cloud-barista/credentials.yaml.enc.:/app/conf/credentials.yaml.enc
      - /docker/cb-tumblebug-container/meta_db/:/app/meta_db/
      - /docker/cb-tumblebug-container/log/:/app/log/
    environment:
      # - TB_ROOT_PATH=/app
      # # Enable TB_SELF_ENDPOINT to specify an endpoint for CB-TB API (default: localhost:1323)
      # # Use public IP if you want to access the API Dashboard from outside of localhost
      # - TB_SELF_ENDPOINT=xxx.xxx.xxx.xxx:1323
      - TB_SPIDER_REST_URL=http://cb-spider:1024/spider
      - TB_ETCD_ENDPOINTS=http://cb-tumblebug-etcd:2379
      - TB_TERRARIUM_REST_URL=http://mc-terrarium:8055/terrarium
      - TB_IAM_MANAGER_REST_URL=http://mc-iam-manager:5000
      # - TB_ETCD_AUTH_ENABLED=false
      # - TB_ETCD_USERNAME=default
      # - TB_ETCD_PASSWORD=default
      - TB_POSTGRES_ENDPOINT=cb-tumblebug-postgres:5432
      - TB_POSTGRES_DATABASE=cb_tumblebug
      - TB_POSTGRES_USER=cb_tumblebug
      - TB_POSTGRES_PASSWORD=cb_tumblebug
      # - TB_TERRARIUM_API_USERNAME=default
      # - TB_TERRARIUM_API_PASSWORD=default
      # - TB_ALLOW_ORIGINS=*
      # - TB_AUTH_ENABLED=true
      # - TB_AUTH_MODE=jwt
      # - TB_API_USERNAME=default
      # - TB_API_PASSWORD=$$2a$$10$$4PKzCuJ6fPYsbCF.HR//ieLjaCzBAdwORchx62F2JRXQsuR3d9T0q
      # - TB_AUTOCONTROL_DURATION_MS=10000
      # - TB_DRAGONFLY_REST_URL=http://cb-dragonfly:9090/dragonfly
      # - TB_DEFAULT_NAMESPACE=default
      # - TB_DEFAULT_CREDENTIALHOLDER=admin
      # - TB_LOGFILE_PATH=/app/log/tumblebug.log
      # - TB_LOGFILE_MAXSIZE=1000
      # - TB_LOGFILE_MAXBACKUPS=3
      # - TB_LOGFILE_MAXAGE=30
      # - TB_LOGFILE_COMPRESS=false
      # - TB_LOGLEVEL=debug
      # - TB_LOGWRITER=both
      # - TB_NODE_ENV=development
    healthcheck: # for CB-Tumblebug
      test: ["CMD", "curl", "-f", "http://localhost:1323/tumblebug/readyz"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # CB-Tumblebug ETCD
  # This is used for storing CB-Tumblebug metadata.
  cb-tumblebug-etcd:
    image: gcr.io/etcd-development/etcd:v3.5.14
    container_name: cb-tumblebug-etcd
    networks:
      - internal_network
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - /docker/etcd/data:/etcd-data
    entrypoint: /usr/local/bin/etcd
    command:
      - --name
      - s1
      - --data-dir
      - /etcd-data
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-advertise-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - s1=http://0.0.0.0:2380
      - --initial-cluster-token
      - tkn
      - --initial-cluster-state
      - new
      - --log-level
      - info
      - --logger
      - zap
      - --log-outputs
      - stderr
      - --auth-token
      - simple
    healthcheck: # for etcd
      test: ["CMD", "/usr/local/bin/etcd", "--version"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # CB-Tumblebug PostgreSQL
  # This is used for storing CB-Tumblebug Spec and Image.
  cb-tumblebug-postgres:
    image: postgres:16-alpine
    container_name: cb-tumblebug-postgres
    restart: always
    networks:
      - internal_network
      # # Enable external network for outbound access (not ideal for security)
      # - external_network
    ports:
      - 5432:5432
    volumes:
      - /docker/cb-tumblebug-container/meta_db/postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cb_tumblebug
      - POSTGRES_PASSWORD=cb_tumblebug
      - POSTGRES_DB=cb_tumblebug
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cb_tumblebug"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # CB-Spider
  cb-spider:
    image: cloudbaristaorg/cb-spider:0.10.8
    container_name: cb-spider
    # build:
    #   context: ../cb-spider
    #   dockerfile: Dockerfile
    networks:
      - internal_network
      - external_network # for outbound access (not ideal for security)
    # expose:
    #   - 1024
    ports:
      - 1024:1024
    volumes:
      - /docker/cb-spider_azure_monitoring/meta_db/:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/
      - /docker/cb-spider_azure_monitoring/log/:/root/go/src/github.com/cloud-barista/cb-spider/log/
    environment:
      - PLUGIN_SW=OFF
      - SERVER_ADDRESS=0.0.0.0:1024
      # if you leave these values empty, REST Auth will be disabled.
      # - API_USERNAME=
      # - API_PASSWORD=
      - SPIDER_LOG_LEVEL=error
      - SPIDER_HISCALL_LOG_LEVEL=error
      - ID_TRANSFORM_MODE=OFF
    healthcheck: # for CB-Spider
      test: ["CMD", "curl", "-f", "http://localhost:1024/spider/readyz"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  influxdb:
    image: influxdb:1.11.8
    container_name: mc-o11y-influx
    restart: always
    ports:
      - 8086:8086
      - 8082:8082
    environment:
      - INFLUXDB_USER=mc-agent
      - INFLUXDB_PASSWORD=mc-agent
      - INFLUXDB_DB="mc-observability"
    volumes:
      - /docker/influxdb/config:/etc/influxdb
      - /docker/influxdb/var/lib/influxdb:/root/.influxdb
      - ./influxdb_init:/docker-entrypoint-initdb.d
    networks:
      - internal_network
      - external_network

  chronograf:
    image: chronograf:1.9.4
    container_name: mc-o11y-chronograf
    restart: always
    ports:
      - 8888:8888
    volumes:
      - /docker/chronograf_data:/var/lib/chronograf
    networks:
      - internal_network
      - external_network

  kapacitor:
    image: kapacitor:1.7.5
    container_name: mc-o11y-kapacitor
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://mc-o11y-influx:8086
    volumes:
      - /docker/kapacitor_data:/var/lib/kapacitor
    networks:
      - internal_network
      - external_network

  opensearch-node1:
    image: opensearchproject/opensearch:1.3.19
    container_name: opensearch-node1
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /docker/opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - internal_network
      - external_network
        
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.19
    container_name: opensearch-dashboards
    restart: always
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - internal_network
      - external_network

  mc-o11y-insight:
    image: cloudbaristaorg/mc-o11y-insight:edge
    container_name: mc-o11y-insight-service
    restart: always
    ports:
      - 9001:9001
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ../python/insight/log:/mc-insight/log
    networks:
      - internal_network
      - external_network

  mc-o11y-insight-scheduler:
    image: cloudbaristaorg/mc-o11y-insight-scheduler:edge
    container_name: mc-o11y-insight-scheduler
    restart: always
    ports:
      - 9002:9002
    environment:
      - TZ=Asia/Seoul
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://mc-agent:mc-agent@mc-observability-maria:3306/mc_airflow
    networks:
      - internal_network
      - external_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: >
      /bin/bash -c "
        # Wait for MySQL
        sleep 10

        # Clean up pid
        rm -f airflow-webserver.pid

        # Set up metadata database
        airflow db migrate

        # Create default user
        airflow users create --username admin --password admin --email admin@innogrid.com --firstname admin --lastname admin --role Admin

        # Import variables & Make connections
        airflow variables set --description 'O11Y Manger API BASE URL' API_BASE_URL http://mc-o11y-manager:18080/api/o11y

        airflow connections add --conn-type http --conn-host mc-o11y-insight-service --conn-schema http --conn-port 9001 api_base_url
        airflow connections add --conn-type mysql --conn-host mariadb --conn-schema mc_observability --conn-login mc-agent --conn-password mc-agent --conn-port 3306 mcmp_db
        airflow connections add --conn-type influxdb --conn-host mc-o11y-influx --conn-port 8086 --conn-schema downsampling --conn-login mc-agent --conn-password mc-agent influxdb

        # Reload & Run dags
        airflow dags reserialize
        airflow dags unpause anomaly_detection
        airflow dags unpause down_sampling

        # Start airflow
        airflow scheduler & airflow webserver -p 9002

        # Keep the server on no matter what
        sleep infinity
            "
