project:
  version: 0.2.0

server:
  port: 18080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://0.0.0.0:3306
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: apis.html
  paths-to-match:
    - /api/**

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: simple
    default-statement-timeout: 100
    map-underscore-to-camel-case: true
  type-aliases-package: mcmp.mc.observability.mco11yagent.monitoring.model, mcmp.mc.observability.mco11yagent.monitoring.dto
  type-handlers-package: mcmp.mc.observability.mco11yagent.monitoring.util

logging:
  level:
    root: INFO
  file:
    path: /var/log/mc-agent
    name: mc-agent.log