project:
  version: 0.2.0

server:
  port: 18080


otel:
  exporter:
    otlp:
      endpoint: ${TEMPO_URL:http://tempo:4318}http://<tempo ip>:4318
      compression: gzip
      protocol: grpc
  logs:
    exporter: none
  metrics:
    exporter: none
  resource:
    attributes:
      service.name: mc-o11y-manager-tracing
  instrumentation:
    micrometer:
      enabled: true



feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 30000
      cb-tumblebug:
        connect-timeout: 5000
        read-timeout: 600000
  agent-manager:
    url: http://localhost:18081
  cb-tumblebug:
    url: ${TUMBLEBUG_URL:http://cb-tumblebug:1323}
    id: ${TUMBLEBUG_ID:default}
    pw: ${TUMBLEBUG_PW:default}
  cb-spider:
    url: ${SPIDER_URL:http://cb-spider:1024}
    id: ${SPIDER_ID:}
    pw: ${SPIDER_PW:}
  insight:
    url: ${INSIGHT_URL:http://mc-observability-insight:9001}
