project:
  version: 0.2.0

server:
  port: 18080

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 30000
      cb-tumblebug:
        connect-timeout: 5000
        read-timeout: 100000
  agent-manager:
    url: http://localhost:18081
  cb-tumblebug:
    url: ${TUMBLEBUG_URL:http://cb-tumblebug:1323}
    id: ${TUMBLEBUG_ID:default}
    pw: ${TUMBLEBUG_PW:default}
  insight:
    url: http://localhost:9001
