services:
  scheduler:
    container_name: insight_scheduler
    image: insight-scheduler:v0.3.0
    restart: always
    environment:
      - TZ=Asia/Seoul
    command: >
      /bin/bash -c "
        # Wait for MySQL
        sleep 10

        # Clean up pid
        rm -f airflow-webserver.pid

        # Set up metadata database
        airflow db migrate

        # Create default user
        airflow users create --username admin --password admin --email admin@innogrid.com --firstname admin --lastname admin --role Admin

        # Import variables & Make connections
        # airflow variables import -a overwrite /usr/local/airflow/airflow_variables.json

        airflow connections add --conn-type http --conn-host 192.168.170.224 --conn-schema http --conn-port 9001 api_base_url
        airflow connections add --conn-type mysql --conn-host 127.0.0.1  --conn-schema mcmp --conn-login mcmp --conn-password 1234 --conn-port 3306 mcmp_db

        # Reload & Run dags
        airflow dags reserialize
        # airflow dags unpause 

        # Start airflow
        airflow scheduler & airflow webserver -p 9002

        # Keep the server on no matter what
        sleep infinity
            "
    volumes:
      - ./airflow-home:/usr/local/airflow
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIRECTORY/volume/iputils:/iputils:ro
    network_mode: "host"


